Vagrant.configure("2") do |config| #"2" ist die Vagrantversion
  config.vm.define "database" do |db|
    db.vm.box = "ubuntu/xenial64"
    db.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    db.vm.hostname = "db01"
    db.vm.network "private_network", ip: "192.168.10.100"
    db.vm.provision "shell", path: "db.sh"
  end

  config.vm.define "web" do |web|
    web.vm.box = "ubuntu/xenial64"
    web.vm.hostname = "web01"
    web.vm.network "private_network", ip:"192.168.10.101"
    web.vm.network "forwarded_port", guest:80, host:8080, auto_correct: true
    web.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
    end
    web.vm.provision "shell", path: "web.sh"
  end
end
      